### ISSUE TITLE
Autoclicker stopped working

### ISSUE THREAD

**Issue by urbanbiscuit** [xinitrc-dev/twitch-points-autoclicker#11]
The autoclicker has stopped working as of 8/7.  Refreshing the page and disabling/enabling the addon doesn't help.

**Comment by xinitrc-dev** [comment]
gotcha. investigating

**Comment by ArnoStrouwen** [comment]
I tested on linux and windows both firefox and chromium, all stopped working.

**Comment by xinitrc-dev** [comment]
Yup, found the problem: Twitch has slightly changed the layout of things. I have made the necessary changes, the new version should be uploaded to the webstores shortly.
0be68bdc6964859d074fe53ec0288c21b6a544d9
