### ISSUE TITLE
Points not Auto Collecting

### ISSUE THREAD

**Issue by LogicalSoIutions** [xinitrc-dev/twitch-points-autoclicker#13]
Points just stopped collecting for me on 3 different machines.

**Comment by xinitrc-dev** [comment]
Any errors in the console log from the extension? (F12->console)

**Comment by LogicalSoIutions** [comment]
Weird. It wasn't collecting for 2 hours. Restarted machines and re-installed browser extension and working fine now. Before restart it would never print "Element detected."

**Comment by xinitrc-dev** [comment]
Weird, thanks for double checking tho!
