### ISSUE TITLE
Not autoclicking in Chrome anymore

### ISSUE THREAD

**Issue by UltraJohn** [xinitrc-dev/twitch-points-autoclicker#16]
Since around the time of the newest update, the autoclicker has stopped clicking automatically.

Google Chrome version 87.0.4280.141 (64bit)

![image](https://user-images.githubusercontent.com/32612142/104822815-b48c1880-5845-11eb-9d8e-19c6b9b83e7b.png)
![image](https://user-images.githubusercontent.com/32612142/104822828-bd7cea00-5845-11eb-92b1-c899e6024f98.png)

**Comment by xinitrc-dev** [comment]
uhh, i dont see how it could fail, unless something is blocking it. Also this bit was not changed at all during the new update. Can you check if there are any errors by right clicking the extension icon->manage extension->collect errors.

**Comment by UltraJohn** [comment]
Well I enabled that but I don't see any errors. The only message in the console is literally just the initialize message. It is still not autoclicking for me. Surely it doesn't get broken by extensions such as ublock or bttv/ffz? I've made no changes to my extensions since it started happening.

**Comment by UltraJohn** [comment]
I installed the normal version (was using lite) and now it works. Not sure why though? There might be an issue with the lite version, unless it's intended behavior somehow due to the missing permissions?

**Comment by xinitrc-dev** [comment]
OH, you should've specifies the version! Will look into it later today

**Comment by UltraJohn** [comment]
Right I forgot about that initially as it didn't mention it in the bug report guideline. Might wanna add that too. :)

**Comment by xinitrc-dev** [comment]
Alrighty, added the version to the template and I think the culprit was page not being loaded properly in time. Added 10 seconds of delay, just like on the release version, and it have worked in my testing. Pushing the new update to the chrome webstore, you'll see it when they approve it :)
