### ISSUE TITLE
New red bonus button that doesn't auto-click

### ISSUE THREAD

**Issue by louis6321** [xinitrc-dev/twitch-points-autoclicker#2]
I just got this red bonus button that didn't auto-click. The blueish-coloured ones auto-click fine.
This red one still awarded the normal 100 points (as I'm a sub to the channel in question).

![](https://i.imgur.com/1OAWS4Z.png)

**Comment by xinitrc-dev** [comment]
Thank you for bringing this up! From what I can gather, those are subscriber-only buttons, and as such I will only be able to test them when the streamers I am subscribed will go live, which will be tomorrow evening (EST timezone). I will investigate and fix as fast as I can!

**Comment by xinitrc-dev** [comment]
I would also highly appreciate if anyone can provide HTML code for the following element, while the red chest button is shown
![chrome_2019-11-28_05-42-46](https://user-images.githubusercontent.com/14354528/69799875-1c932180-11a2-11ea-800f-87afe7181d53.png)

**Comment by louis6321** [comment]
![image](https://user-images.githubusercontent.com/43100308/69970173-b66b1d80-1558-11ea-9330-6a317901491c.png)

Hopefully this is what you need?

**Comment by louis6321** [comment]
![image](https://user-images.githubusercontent.com/43100308/69970251-e4e8f880-1558-11ea-8f8d-a71edf2550cb.png)

More nested stuff

**Comment by xinitrc-dev** [comment]
Thank you for the code provided! I have modified and broadened the way I detect buttons, which should fix your issue! 85f280218eab76404512c08cd983a7c106ca8c61
Will be releasing a new update on all webstores shortly.
