### ISSUE TITLE
Alternate Player for Twitch.tv

### ISSUE THREAD

**Issue by pepek1122583** [xinitrc-dev/twitch-points-autoclicker#3]
Hi.
Can you customize your Clicker or make compatible with this add-on?
https://chrome.google.com/webstore/detail/alternate-player-for-twit/bhplkbgoehhhddaoolmakpocnenplmhf
Thanks

**Comment by xinitrc-dev** [comment]
Unfortunately, I cannot. The way that extension works does not allow any other extension to integrate with it.
See: https://github.com/xinitrc-dev/twitch-points-autoclicker/issues/1

**Comment by pepek1122583** [comment]
Sorry for opening but Better TTv Working good with this addon O.o
