### ISSUE TITLE
Don't work ?

### ISSUE THREAD

**Issue by Glaived** [xinitrc-dev/twitch-points-autoclicker#4]
the extension doesn't seem to be working anymore, I don't have a console error, can you look at it from your side?

HTML Tree : https://hastebin.com/gedodigovo.xml

**Comment by xinitrc-dev** [comment]
Did you access the channel page directly?
There is a known issue of the script failing to start when you go, for example, from the main page and click on a stream there.
Try restarting the page and let me know if it still doesn't work.
Your HTML snippet doesn't seem to be out of ordinary, meaning it should work as usual.

**Comment by xinitrc-dev** [comment]
Closing for the absence of followup feedback and CNR.
Comment, if you want it reopened.
