### ISSUE TITLE
New configuration option: Make grouping separator configurable

### ISSUE THREAD

**Issue by mohmaniac** [xinitrc-dev/twitch-points-autoclicker#5]
Auto Clicking works very well, but counting and displaying earned points seems to be locale agnostic:
Currently, the points are expected in the form 'xx,xxx sssssss' - but this comma - the grouping separator - seems to depend on the browser locale. Here, for example: 'xxx.xxxx ssss' (de_de). In this case, points are not really parseable.

https://github.com/xinitrc-dev/twitch-points-autoclicker/blob/9f33c5fd30a6a704073fb8b7bf2e1d4498f56a12/src/twitch-clicker.js#L9

Maybe its possible to add a configuration option to override the currently (regex-) hard coded separator.

Thanks a lot!

**Comment by xinitrc-dev** [comment]
Awesome catch! Since there is no dot separators when there are comma ones or vice versa, I could just first replace all the dots with commas, so I don't rely on user setting. I will update it tomorrow tho, there are some more kinks I gotta iron out with those points parsing. Thanks again!

**Comment by xinitrc-dev** [comment]
Fixed in 815b4a13fa0cf1e80dd0f86d0568792c50a8719b 
Will be releasing it as 1.5.2 on all webstores shortly
